language: ruby
addons:
  postgresql: 9.4
env:
  - RAILS_ENV=test
bundler_args: --without production development
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database recruitment_agency_test;' -U postgres
  - bundle exec rake db:setup
script: bundle exec rspec
